INSERT INTO a_club(id,
                   cname,
                   ctime,
                   homefield,
                   coach,
                   builder,
                   imgurl,
                   location)
     VALUES (1,
             'Manchester United',
             '1878-01-01',
             'Old Trafford',
             'David Moyes',
             NULL,
             'images/manchesterunited.png',
             'Manchester City,England');INSERT INTO a_club(id,
                   cname,
                   ctime,
                   homefield,
                   coach,
                   builder,
                   imgurl,
                   location)
     VALUES (2,
             'Chelsea',
             '1905-03-10',
             'Stamford Bridge Stadium',
             'Jose Mario dos Santos Mourinho Felix',
             'Henry Augustus Mears',
             'images/chelsea.png',
             'London,England');INSERT INTO a_club(id,
                   cname,
                   ctime,
                   homefield,
                   coach,
                   builder,
                   imgurl,
                   location)
     VALUES (3,
             'Arsenal',
             '1886-00-00',
             'Emirates Stadium',
             'Arsene Wenger',
             NULL,
             'images/arsenal.png',
             'North London,England');INSERT INTO a_club(id,
                   cname,
                   ctime,
                   homefield,
                   coach,
                   builder,
                   imgurl,
                   location)
     VALUES (4,
             'Liverpool',
             '1892-03-15',
             'Anfield Stadium',
             'Brendan Rodgers',
             'John Houlding',
             'images/liverpool.png',
             'Liverpool,England');INSERT INTO a_club(id,
                   cname,
                   ctime,
                   homefield,
                   coach,
                   builder,
                   imgurl,
                   location)
     VALUES (5,
             'Manchester City',
             '1894-00-00',
             'Etihad Stadium',
             'Manuel Luis Pellegrini Ripamonti',
             NULL,
             'images/mcfc.png',
             'Manchester City,England');INSERT INTO a_club(id,
                   cname,
                   ctime,
                   homefield,
                   coach,
                   builder,
                   imgurl,
                   location)
     VALUES (6,
             'Tottenham Hotspur',
             '1882-00-00',
             'White Hart Lane',
             'Villas Boas',
             NULL,
             'images/tottenhamhotspur.png',
             'North London,England');INSERT INTO a_club(id,
                   cname,
                   ctime,
                   homefield,
                   coach,
                   builder,
                   imgurl,
                   location)
     VALUES (7,
             'Aston Villa',
             '1874-00-00',
             'Villa Park',
             'Paul Lambert',
             NULL,
             'images/avfc.png',
             'Birmingham,England');INSERT INTO a_club(id,
                   cname,
                   ctime,
                   homefield,
                   coach,
                   builder,
                   imgurl,
                   location)
     VALUES (8,
             'Everton',
             '1878-01-01',
             'Goodison Park',
             'Roberto Martinez',
             NULL,
             'images/everton.png',
             'Liverpool,England');INSERT INTO a_club(id,
                   cname,
                   ctime,
                   homefield,
                   coach,
                   builder,
                   imgurl,
                   location)
     VALUES (9,
             'Crystal Palace',
             '1905-00-00',
             'Selhurst Park',
             'Ian Scott Holloway',
             NULL,
             'images/crystalpalace.png',
             'South London,England');INSERT INTO a_club(id,
                   cname,
                   ctime,
                   homefield,
                   coach,
                   builder,
                   imgurl,
                   location)
     VALUES (10,
             'Sunderland Association',
             '1879-00-00',
             'Stadium of Light',
             'Paolo Di Canio',
             NULL,
             'images/sunderland.png',
             'Sunderland,England');INSERT INTO a_club(id,
                   cname,
                   ctime,
                   homefield,
                   coach,
                   builder,
                   imgurl,
                   location)
     VALUES (11,
             'Southampton',
             '1885-11-00',
             'St. Mary''s Stadiu',
             'Pochettino',
             NULL,
             'images/southampton.png',
             'Southampton,England');INSERT INTO a_club(id,
                   cname,
                   ctime,
                   homefield,
                   coach,
                   builder,
                   imgurl,
                   location)
     VALUES (12,
             'Newcastle United',
             '1881-00-00',
             'St James'' Park',
             'Alan Pardew',
             NULL,
             'images/newcastleunited.png',
             'Newcastle,England');INSERT INTO a_club(id,
                   cname,
                   ctime,
                   homefield,
                   coach,
                   builder,
                   imgurl,
                   location)
     VALUES (13,
             'West Ham United',
             '1895-00-00',
             'Upton Park',
             'Sam Allardyce',
             'Dave Taylo,Arnold Hills',
             'images/westhamunited.png',
             'Outer London,England');INSERT INTO a_club(id,
                   cname,
                   ctime,
                   homefield,
                   coach,
                   builder,
                   imgurl,
                   location)
     VALUES (14,
             'Stoke City',
             '1868-00-00',
             'The Britannia Stadium',
             'Mark Hughes',
             NULL,
             'images/stokecity.png',
             'Stoke-on-Trent,England');INSERT INTO a_club(id,
                   cname,
                   ctime,
                   homefield,
                   coach,
                   builder,
                   imgurl,
                   location)
     VALUES (15,
             'West Bromwich Albion',
             '1878-00-00',
             'The Hawthorns',
             'Steve Clarke',
             NULL,
             'images/westbromwich.png',
             'West Bromwich,England');INSERT INTO a_club(id,
                   cname,
                   ctime,
                   homefield,
                   coach,
                   builder,
                   imgurl,
                   location)
     VALUES (16,
             'Swansea City',
             '1912-00-00',
             'Liberty Stadium',
             'Michael Laudrup',
             NULL,
             'images/swansea.png',
             'Swansea,Wales');INSERT INTO a_club(id,
                   cname,
                   ctime,
                   homefield,
                   coach,
                   builder,
                   imgurl,
                   location)
     VALUES (17,
             'Hull City Association',
             '1904-00-00',
             'Kingston Communications Stadium',
             'Bruce',
             NULL,
             'images/hullcity.png',
             'Hull City,England');INSERT INTO a_club(id,
                   cname,
                   ctime,
                   homefield,
                   coach,
                   builder,
                   imgurl,
                   location)
     VALUES (18,
             'Queens Park Rangers',
             '1882-00-00',
             'Loftus Road',
             'Henry Redknapp',
             NULL,
             'images/queensparkrangers.png',
             'Hammersmith,England');INSERT INTO a_club(id,
                   cname,
                   ctime,
                   homefield,
                   coach,
                   builder,
                   imgurl,
                   location)
     VALUES (19,
             'Leicester City',
             '1884-00-00',
             'King Power Stadium',
             'Nigel Graham Pearson',
             NULL,
             'images/leicestercity.png',
             'Leicester City,England');INSERT INTO a_club(id,
                   cname,
                   ctime,
                   homefield,
                   coach,
                   builder,
                   imgurl,
                   location)
     VALUES (20,
             'Burnley',
             '1882-00-00',
             'Turf Moor',
             'Sean Dyche',
             NULL,
             'images/burnley.png',
             'Burnley,England');INSERT INTO a_gameresult(id,
                         pname,
                         cname,
                         pgoal,
                         cgoal,
                         gametime,
                         field,
                         leg,
                         msg)
     VALUES (1,
             'Manchester United',
             'Swansea City',
             1,
             2,
             '2014-08-16',
             'Old Trafford',
             1,
             '
GOAL:Swansea City_Ki_FIRST-HALF_28
GOAL:Manchester United_Rooney_SECOND-HALF_8
GOAL:Swansea City_Sigurdsson_SECOND-HALF_27');INSERT INTO a_gameresult(id,
                         pname,
                         cname,
                         pgoal,
                         cgoal,
                         gametime,
                         field,
                         leg,
                         msg)
     VALUES (2,
             'West Ham United',
             'Tottenham Hotspur',
             0,
             1,
             '2014-08-16',
             'Upton Park',
             1,
             '
GOAL:Tottenham Hotspur_Dier_SECOND-STOPPAGE_3');INSERT INTO a_scoreboard(id,
                         name,
                         win,
                         faith,
                         tie,
                         score,
                         gain,
                         lose,
                         imageurl)
     VALUES (1,
             'Manchester United',
             0,
             1,
             0,
             0,
             1,
             2,
             'images/manchesterunited.png');INSERT INTO a_scoreboard(id,
                         name,
                         win,
                         faith,
                         tie,
                         score,
                         gain,
                         lose,
                         imageurl)
     VALUES (2,
             'Chelsea',
             0,
             0,
             0,
             0,
             0,
             0,
             'images/chelsea.png');INSERT INTO a_scoreboard(id,
                         name,
                         win,
                         faith,
                         tie,
                         score,
                         gain,
                         lose,
                         imageurl)
     VALUES (3,
             'Arsenal',
             0,
             0,
             0,
             0,
             0,
             0,
             'images/arsenal.png');INSERT INTO a_scoreboard(id,
                         name,
                         win,
                         faith,
                         tie,
                         score,
                         gain,
                         lose,
                         imageurl)
     VALUES (4,
             'Liverpool',
             0,
             0,
             0,
             0,
             0,
             0,
             'images/liverpool.png');INSERT INTO a_scoreboard(id,
                         name,
                         win,
                         faith,
                         tie,
                         score,
                         gain,
                         lose,
                         imageurl)
     VALUES (5,
             'Manchester City',
             0,
             0,
             0,
             0,
             0,
             0,
             'images/mcfc.png');INSERT INTO a_scoreboard(id,
                         name,
                         win,
                         faith,
                         tie,
                         score,
                         gain,
                         lose,
                         imageurl)
     VALUES (6,
             'Tottenham Hotspur',
             1,
             0,
             0,
             3,
             1,
             0,
             'images/tottenhamhotspur.png');INSERT INTO a_scoreboard(id,
                         name,
                         win,
                         faith,
                         tie,
                         score,
                         gain,
                         lose,
                         imageurl)
     VALUES (7,
             'Aston Villa',
             0,
             0,
             0,
             0,
             0,
             0,
             'images/avfc.png');INSERT INTO a_scoreboard(id,
                         name,
                         win,
                         faith,
                         tie,
                         score,
                         gain,
                         lose,
                         imageurl)
     VALUES (8,
             'Everton',
             0,
             0,
             0,
             0,
             0,
             0,
             'images/everton.png');INSERT INTO a_scoreboard(id,
                         name,
                         win,
                         faith,
                         tie,
                         score,
                         gain,
                         lose,
                         imageurl)
     VALUES (9,
             'Crystal Palace',
             0,
             0,
             0,
             0,
             0,
             0,
             'images/crystalpalace.png');INSERT INTO a_scoreboard(id,
                         name,
                         win,
                         faith,
                         tie,
                         score,
                         gain,
                         lose,
                         imageurl)
     VALUES (10,
             'Sunderland Association',
             0,
             0,
             0,
             0,
             0,
             0,
             'images/sunderland.png');INSERT INTO a_scoreboard(id,
                         name,
                         win,
                         faith,
                         tie,
                         score,
                         gain,
                         lose,
                         imageurl)
     VALUES (11,
             'Southampton',
             0,
             0,
             0,
             0,
             0,
             0,
             'images/southampton.png');INSERT INTO a_scoreboard(id,
                         name,
                         win,
                         faith,
                         tie,
                         score,
                         gain,
                         lose,
                         imageurl)
     VALUES (12,
             'Newcastle United',
             0,
             0,
             0,
             0,
             0,
             0,
             'images/newcastleunited.png');INSERT INTO a_scoreboard(id,
                         name,
                         win,
                         faith,
                         tie,
                         score,
                         gain,
                         lose,
                         imageurl)
     VALUES (13,
             'West Ham United',
             0,
             1,
             0,
             0,
             0,
             1,
             'images/westhamunited.png');INSERT INTO a_scoreboard(id,
                         name,
                         win,
                         faith,
                         tie,
                         score,
                         gain,
                         lose,
                         imageurl)
     VALUES (14,
             'Stoke City',
             0,
             0,
             0,
             0,
             0,
             0,
             'images/stokecity.png');INSERT INTO a_scoreboard(id,
                         name,
                         win,
                         faith,
                         tie,
                         score,
                         gain,
                         lose,
                         imageurl)
     VALUES (15,
             'West Bromwich Albion',
             0,
             0,
             0,
             0,
             0,
             0,
             'images/westbromwich.png');INSERT INTO a_scoreboard(id,
                         name,
                         win,
                         faith,
                         tie,
                         score,
                         gain,
                         lose,
                         imageurl)
     VALUES (16,
             'Swansea City',
             1,
             0,
             0,
             3,
             2,
             1,
             'images/swansea.png');INSERT INTO a_scoreboard(id,
                         name,
                         win,
                         faith,
                         tie,
                         score,
                         gain,
                         lose,
                         imageurl)
     VALUES (17,
             'Hull City Association',
             0,
             0,
             0,
             0,
             0,
             0,
             'images/hullcity.png');INSERT INTO a_scoreboard(id,
                         name,
                         win,
                         faith,
                         tie,
                         score,
                         gain,
                         lose,
                         imageurl)
     VALUES (18,
             'Queens Park Rangers',
             0,
             0,
             0,
             0,
             0,
             0,
             'images/queensparkrangers.png');INSERT INTO a_scoreboard(id,
                         name,
                         win,
                         faith,
                         tie,
                         score,
                         gain,
                         lose,
                         imageurl)
     VALUES (19,
             'Leicester City',
             0,
             0,
             0,
             0,
             0,
             0,
             'images/leicestercity.png');INSERT INTO a_scoreboard(id,
                         name,
                         win,
                         faith,
                         tie,
                         score,
                         gain,
                         lose,
                         imageurl)
     VALUES (20,
             'Burnley',
             0,
             0,
             0,
             0,
             0,
             0,
             'images/burnley.png');INSERT INTO a_shotboard(id,
                        name,
                        cname,
                        goals,
                        cc)
     VALUES (1,
             'Ki',
             'Swansea City',
             1,
             'Swansea City_Ki');INSERT INTO a_shotboard(id,
                        name,
                        cname,
                        goals,
                        cc)
     VALUES (2,
             'Rooney',
             'Manchester United',
             1,
             'Manchester United_Rooney');INSERT INTO a_shotboard(id,
                        name,
                        cname,
                        goals,
                        cc)
     VALUES (3,
             'Sigurdsson',
             'Swansea City',
             1,
             'Swansea City_Sigurdsson');INSERT INTO a_shotboard(id,
                        name,
                        cname,
                        goals,
                        cc)
     VALUES (4,
             'Dier',
             'Tottenham Hotspur',
             1,
             'Tottenham Hotspur_Dier');INSERT INTO a_sporter(id,
                      name,
                      cname,
                      born,
                      country,
                      sendclub,
                      band,
                      imgname,
                      number,
                      role)
     VALUES (2,
             'Rooney',
             'Manchester United',
             '1985-10-24',
             ' England',
             'no',
             'A',
             '201471623124950.jpg',
             10,
             'forward');INSERT INTO a_sporter(id,
                      name,
                      cname,
                      born,
                      country,
                      sendclub,
                      band,
                      imgname,
                      number,
                      role)
     VALUES (3,
             'Ki',
             'Swansea City',
             '1989-01-24',
             'South Korea',
             'no',
             'A',
             '20147162323085.jpg',
             4,
             'midfielder');INSERT INTO a_sporter(id,
                      name,
                      cname,
                      born,
                      country,
                      sendclub,
                      band,
                      imgname,
                      number,
                      role)
     VALUES (4,
             'Sigurdsson',
             'Swansea City',
             '1989-09-09',
             'Iceland',
             'no',
             'A',
             '201471623255210.jpg',
             23,
             'midfielder');INSERT INTO a_sporter(id,
                      name,
                      cname,
                      born,
                      country,
                      sendclub,
                      band,
                      imgname,
                      number,
                      role)
     VALUES (5,
             'Dier',
             'Tottenham Hotspur',
             '1994-01-15',
             'England',
             'no',
             'A',
             '2014717051876.jpg',
             15,
             'back');INSERT INTO a_sporter(id,
                      name,
                      cname,
                      born,
                      country,
                      sendclub,
                      band,
                      imgname,
                      number,
                      role)
     VALUES (6,
             'Chester',
             'Hull City Association',
             '1989-01-23',
             'wales',
             'no',
             'A',
             '20147170285646.jpg',
             5,
             'back');COMMIT;